# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67c2d8c596a85f94eb7b1fd4ac4dbd877739073a035b4c20a560d42b272a0b5e4db2fec0a1380761bfd2eee71908ff2ab579298007c352da44cfce8ccfc67b73

test:
  secret_key_base: 9d313819f14ea80d5cc892b73273c01fca5faf4c3062b890575d08c0574e55ecaaededeb25571690a4b98b327d994e8c203c260712615dbbc354644f62cf1205

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
